Image mosaic clean script.
geosolutions-it/eumetsat-EOWS pull request #477
Opened 2021-04-23 11:27 UTC by agpenton

- Function to check and create the connection to PostgreSQL.
- Function to query and delete the entries in the database and the files in the filesystem.
- Function to send an email after the process finished.
- Files added:
    -   .env file to declare the variables.
    - Dockerfile to create an image.
    - requirements.txt to install the python modules.
    - the python script.

2021-04-23 13:28 UTC, randomorder requested changes
too inefficient at the moment
please check my comments

2021-04-23 13:28 UTC, randomorder commented on scripts/python/housekeeper/housekeeper.py
> +            for x in curs.fetchall():
Better to fetch the results and process them in small batches instead of all at once.

These tables can potentially contain many many rows. The "fetch size" must be configurable

2021-04-23 13:28 UTC, randomorder commented on scripts/python/housekeeper/housekeeper.py
> +            curs.execute(sql_query)
this is very inefficient

Use a filter in the query to find the tuples that need to be deleted based on a filter on the time attribute

2021-04-23 13:28 UTC, randomorder commented on scripts/python/housekeeper/housekeeper.py
> +                if mod_date < datetime.timestamp(datetime_object):
See comment above 

Use a filter in the query to find the tuples that need to be deleted based on a filter on the time attribute

2021-04-23 13:28 UTC, randomorder commented on scripts/python/housekeeper/housekeeper.py
> +                    conn.commit()  # commiting the operation.
Closing the connection every time is very inefficient. Please batch the operations instead

2021-04-23 13:28 UTC, randomorder commented on scripts/python/housekeeper/housekeeper.py
> +                    os.remove(filename)
if possible (not sure) find a way to batch delete multiple files at once

2021-04-26 13:17 UTC, agpenton commented on scripts/python/housekeeper/housekeeper.py
> +    sql_query = f'SELECT "location", ingestion FROM {table};'
fixed here https://github.com/geosolutions-it/eumetsat-EOWS/pull/477/commits/5505cf4cf395b5b39905a390d7a7868c7e9b2243

2021-04-26 13:18 UTC, agpenton commented on scripts/python/housekeeper/housekeeper.py
> +            curs.execute(sql_query)
fixed here https://github.com/geosolutions-it/eumetsat-EOWS/pull/477/commits/5505cf4cf395b5b39905a390d7a7868c7e9b2243

2021-04-26 13:18 UTC, agpenton commented on scripts/python/housekeeper/housekeeper.py
> +                if mod_date < datetime.timestamp(datetime_object):
fixed here https://github.com/geosolutions-it/eumetsat-EOWS/pull/477/commits/5505cf4cf395b5b39905a390d7a7868c7e9b2243

2021-04-26 13:20 UTC, agpenton commented on scripts/python/housekeeper/housekeeper.py
> +                    conn.commit()  # commiting the operation.
till the commit command doesn't run, the changes will not be applied.

2021-04-30 07:47 UTC, randomorder commented on scripts/python/housekeeper/housekeeper.py
> +            for x in curs.fetchall():
Is this still fetching all the rows at once @agpenton ?

2021-04-30 07:48 UTC, randomorder commented on scripts/python/housekeeper/housekeeper.py
> +                with open('files.txt', 'w') as a_writer:
is it really necessary to write to file?

2021-05-11 13:20 UTC, randomorder requested changes

2021-05-12 10:55 UTC, agpenton commented on scripts/python/housekeeper/README.md
> +### Deployment of the script to kubernetes.
solved here https://github.com/geosolutions-it/eumetsat-EOWS/pull/477/commits/ec33315523fb2985277d68e91e666d0ffeaa7b27

2021-05-12 10:55 UTC, agpenton commented on scripts/python/housekeeper/k8s/kustomization.yaml
> +---
solved here https://github.com/geosolutions-it/eumetsat-EOWS/pull/477/commits/ec33315523fb2985277d68e91e666d0ffeaa7b27

2021-05-12 12:05 UTC, agpenton commented
@randomorder the script is ready to review

2021-05-12 13:15 UTC, randomorder requested changes

2021-05-12 13:28 UTC, agpenton commented on scripts/python/housekeeper/helm/imagemosaic-cleaner/values.yaml
> +      LAYERS: '"copernicus:sentinel3b;mosaic_indexes.copernicus_sentinel3a_olci_l2_chl_fullres;360","copernicus:sentinel3b;mosaic_indexes.copernicus_sentinel3b_olci_l1_rgb_fullres;120","copernicus_da
> the name of the time column for each layer is missing

the nomenclatur of the layer configuration was:
`# comment
ALL;<global_retention_hours>
<layer_name>;<mosaic_index_table_1>;<retention_hours_1>
# comment
<layer_name>;<mosaic_index_table_2>;<retention_hours_2>
`
and this is the layer configuration that I put there
`copernicus:sentinel3b;mosaic_indexes.copernicus_sentinel3a_olci_l2_chl_fullres;360`.

2021-05-12 13:30 UTC, agpenton commented on scripts/python/housekeeper/helm/imagemosaic-cleaner/values.yaml
> +#      example.sh: ci/files/example.sh
this is just an example of how to create the configmap.

2021-05-12 13:30 UTC, agpenton commented on scripts/python/housekeeper/housekeeper.py
> +    notification()
ok, i will fix all and push again.

2021-05-12 13:45 UTC, randomorder commented on scripts/python/housekeeper/helm/imagemosaic-cleaner/values.yaml
> +      LAYERS: '"copernicus:sentinel3b;mosaic_indexes.copernicus_sentinel3a_olci_l2_chl_fullres;360","copernicus:sentinel3b;mosaic_indexes.copernicus_sentinel3b_olci_l1_rgb_fullres;120","copernicus_da
yes but I've asked you to add the time column as well. 2 times

2021-05-12 13:45 UTC, randomorder commented on scripts/python/housekeeper/helm/imagemosaic-cleaner/values.yaml
> +#      example.sh: ci/files/example.sh
remove it

2021-05-12 13:46 UTC, randomorder commented on scripts/python/housekeeper/helm/imagemosaic-cleaner/values.yaml
> +      password: "iduzwucgdmhzaecc"
No passwords in GitHub

especially publicly visible ones!

2021-05-13 06:57 UTC, agpenton commented on scripts/python/housekeeper/helm/imagemosaic-cleaner/values.yaml
> +      password: "iduzwucgdmhzaecc"
solved here https://github.com/geosolutions-it/eumetsat-EOWS/pull/477/commits/b871d65fd1c6df556772fde2dcaad89916a60140

2021-05-13 08:52 UTC, agpenton commented on scripts/python/housekeeper/housekeeper.py
> +                    with open('files.txt', 'r') as a_reader:
solved https://github.com/geosolutions-it/eumetsat-EOWS/pull/477/commits/16d7972d6635394e0d6b29a91879671616c055e8

2021-05-13 08:53 UTC, agpenton commented
@randomorder the PR is ready to review.

2021-05-22 16:18 UTC, merged